### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by jsmrcaga** [StephaneBranly/UTRace-Website#16]
Hello les UTCéens!

Hello Stéphane, merci pour le follow.

Tite question, vous êtes sûrs pour le nom de l'asso là ? 👅 
UT'Kart ou autre n'était pas au rdv ?

**Comment by feuloren** [comment]
Laisse l'UTC tranquille stp Jo Colina.

**Comment by StephaneBranly** [comment]
Hey !!!

Merci pour le repo d'IA01 💯 

Quel est le problème avec UT'Race [you-tr-ace] ? 🤔 
Cela nous a demandé beaucoup de réflexion pour trouver le nom :p

**Comment by jsmrcaga** [comment]
Hahaha je savais même pas que j'avais un repo d'IA01. Mais t'es le bienvenu :P 

Effectivement prononcé à l'anglaise ca va mieux, mais en francais j'avais lu [u-té-race] ^^

**Comment by StephaneBranly** [comment]
Ouais c'est vrai qu'en français ça donne différemment, on nous a déjà fait aussi cette remarque ^^
